
--SELECT @@VERSION
--SELECT * FROM sys.schemas

--========================================================
--CREAR TABLAS
--========================================================
CREATE SCHEMA ENCUESTA

CREATE TABLE ENCUESTA.ENCUESTA_ASIGNATURA
(
	ENCUESTA_ID INT PRIMARY KEY IDENTITY(1,1),
	NOMBRE_ENCUESTA VARCHAR(100) NOT NULL,
	DESCRIPCION_ENCUESTA VARCHAR(100) NOT NULL,
  	TIPO_ENCUESTA INT NOT NULL,
	TIPO_ENCUESTADO INT NOT NULL,
	TIPO_PROGRAMA VARCHAR(250) NOT NULL,
	SEDE VARCHAR(50) NOT NULL,
	PERIODO VARCHAR(20) NOT NULL,
	SECCION VARCHAR(20) NOT NULL,
	MODULO VARCHAR(500) NOT NULL,
	DOCENTE VARCHAR(250) NOT NULL,
	FECHA_INICIO DATETIME NOT NULL,
	FECHA_FIN DATETIME NOT NULL,
	ACTIVO BIT NOT NULL,
	FECHA_ENVIO DATETIME DEFAULT GETDATE() NOT NULL,
	USUARIO_ENVIO VARCHAR(50) NOT NULL
)

CREATE TABLE ENCUESTA.ENCUESTA_ASIGNATURA_ALUMNO
(
	ENCUESTA_ID INT PRIMARY KEY IDENTITY(1,1),
	ENCUESTA_ASIGNATURA_ID INT NOT NULL,
	DNI_ENCUESTADO VARCHAR(50),
	COMPLETADO BIT DEFAULT 0 NOT NULL,
	TIPO_ENCUESTADO_ID INT NOT NULL,
	FECHA_RESPUESTA DATETIME NULL,
	FECHA_CREACION DATETIME DEFAULT GETDATE() NOT NULL,
	USUARIO_CREACION VARCHAR(50) NOT NULL
)


CREATE TABLE ENCUESTA.ENCUESTA_PLANTILLA
(
	ENCUESTA_ID INT PRIMARY KEY IDENTITY(1,1),
	NOMBRE_ENCUESTA VARCHAR(100) NOT NULL,
	DESCRIPCION_ENCUESTA VARCHAR(100) NOT NULL,
  	TIPO_ENCUESTA INT NOT NULL,
	ESTADO BIT DEFAULT 1 NOT NULL,
	FECHA_CREACION DATETIME DEFAULT GETDATE() NOT NULL,
	FECHA_MODIFICACION DATETIME NULL,
	USUARIO_CREACION VARCHAR(50) NOT NULL,
	USUARIO_MODIFICACION VARCHAR(50) NULL
)

CREATE TABLE ENCUESTA.TIPO_ENCUESTA
(
	TIPO_ENCUESTA_ID INT PRIMARY KEY IDENTITY(1,1),
	NOMBRE_ENCUESTA VARCHAR(150) NOT NULL,
	ESTADO BIT NOT NULL DEFAULT 1,
	FECHA_CREACION DATETIME DEFAULT GETDATE() NOT NULL,
	FECHA_MODIFICACION DATETIME NULL,
	USUARIO_CREACION VARCHAR(50) NOT NULL,
	USUARIO_MODIFICACION VARCHAR(50) NULL
)

--INSERT INTO ENCUESTA.TIPO_ENCUESTA VALUES
-- ('Satisfacción estudiantil', 1, GETDATE(), NULL, 'sistema', NULL)
--,('Satisfacción docente', 1, GETDATE(), NULL, 'sistema', NULL)
--,('Satisfacción estudiantil inducción', 1, GETDATE(), NULL, 'sistema', NULL)
--,('Modelo académico', 1, GETDATE(), NULL, 'sistema', NULL);

CREATE TABLE ENCUESTA.TIPO_ENCUESTADO
(
	TIPO_ENCUESTADO_ID INT PRIMARY KEY IDENTITY(1,1),
	NOMBRE_ENCUESTADO VARCHAR(150) NOT NULL,
	ESTADO BIT NOT NULL DEFAULT 1,
	FECHA_CREACION DATETIME DEFAULT GETDATE() NOT NULL,
	FECHA_MODIFICACION DATETIME NULL,
	USUARIO_CREACION VARCHAR(50) NOT NULL,
	USUARIO_MODIFICACION VARCHAR(50) NULL
)

--INSERT INTO ENCUESTA.TIPO_ENCUESTADO VALUES
-- ('Estudiante', 1, GETDATE(), NULL, 'sistema', NULL)
--,('Docente', 1, GETDATE(), NULL, 'sistema', NULL)
--,('Administrativo', 1, GETDATE(), NULL, 'sistema', NULL);

CREATE TABLE ENCUESTA.ENCUESTA_BLOQUE_PLANTILLA
(
	BLOQUE_ID INT PRIMARY KEY IDENTITY(1,1),
	ENCUESTA_ID INT NOT NULL,
	TITULO_BLOQUE VARCHAR(200) NOT NULL,
	ORDEN INT NOT NULL,
	ESTADO BIT DEFAULT 1 NOT NULL,
	FECHA_CREACION DATETIME DEFAULT GETDATE() NOT NULL,
	FECHA_MODIFICACION DATETIME NULL,
	USUARIO_CREACION VARCHAR(50) NOT NULL,
	USUARIO_MODIFICACION VARCHAR(50) NULL
)

CREATE TABLE ENCUESTA.ENCUESTA_BLOQUE_ASIGNATURA
(
	BLOQUE_ID INT PRIMARY KEY IDENTITY(1,1),
	ENCUESTA_ID INT NOT NULL,
	TITULO_BLOQUE VARCHAR(200) NOT NULL,
	ORDEN INT NOT NULL,
	FECHA_CREACION DATETIME DEFAULT GETDATE() NOT NULL,
	USUARIO_CREACION VARCHAR(50) NOT NULL
)


CREATE TABLE ENCUESTA.ENCUESTA_PREGUNTA_PLANTILLA
(
	PREGUNTA_ID INT PRIMARY KEY IDENTITY(1,1),
	BLOQUE_ID INT NOT NULL,
	TEXTO_PREGUNTA VARCHAR(200) NOT NULL,
	TIPO_PREGUNTA VARCHAR(MAX) NOT NULL,
	ORDEN INT NOT NULL,
	OPCIONES_JSON VARCHAR(MAX) NOT NULL,
	ESTADO BIT DEFAULT 1 NOT NULL,
	FECHA_CREACION DATETIME DEFAULT GETDATE() NOT NULL,
	FECHA_MODIFICACION DATETIME NULL,
	USUARIO_CREACION VARCHAR(50) NOT NULL,
	USUARIO_MODIFICACION VARCHAR(50) NULL
)

CREATE TABLE ENCUESTA.ENCUESTA_PREGUNTA_ASIGNATURA
(
	PREGUNTA_ID INT PRIMARY KEY IDENTITY(1,1),
	BLOQUE_ID INT NOT NULL,
	TEXTO_PREGUNTA VARCHAR(200) NOT NULL,
	TIPO_PREGUNTA VARCHAR(MAX) NOT NULL,
	ORDEN INT NOT NULL,
	OPCIONES_JSON VARCHAR(MAX) NOT NULL,
	FECHA_CREACION DATETIME DEFAULT GETDATE() NOT NULL,
	USUARIO_CREACION VARCHAR(50) NOT NULL
	
)

CREATE TABLE ENCUESTA.RESPUESTA_ENCUESTA
(
	RESPUESTA_ENCUESTA_ID INT PRIMARY KEY IDENTITY(1,1),
	ENCUESTA_ID INT NOT NULL,
	ALUMNO_ID VARCHAR(50) NOT NULL,
	FECHA_RESPUESTA DATETIME NOT NULL,
	COMPLETADO BIT NOT NULL
)

CREATE TABLE ENCUESTA.RESPUESTA_PREGUNTA
(
	RESPUESTA_PREGUNTA_ID INT PRIMARY KEY IDENTITY(1,1),
	RESPUESTA_ENCUESTA_ID INT NOT NULL,
	ENCUESTA_PREGUNTA_ID INT NOT NULL,
	VALOR_RESPUESTA VARCHAR(MAX) NOT NULL
)

--CREATE TABLE ENCUESTA.VALORES_CORREO
--(
--	VALORES_CORREO_ID INT PRIMARY KEY IDENTITY(1,1),
--	ENCUESTA_ID INT NULL,
--	USER_EMAIL VARCHAR(100) NULL,
--	TO_EMAIL VARCHAR(MAX) NULL,
--	NOMBRE_ENCUESTA VARCHAR(200) NULL,
--	NSUBJECT VARCHAR(200) NOT NULL,
--	BODY VARCHAR(MAX) NULL
--)

--DROP TABLE ENCUESTA.VALORES_CORREO

--INSERT INTO ENCUESTA.VALORES_CORREO
--VALUES (NULL, 'emisoropcional@gmail.com', 'remitente@gmail.com', 'Nombre Encuesta desde BD', 'TITULO SUBJECT DESDE BD', 'CONTENIDO ADJUNTAR LINK PARA ENCUESTAS');
