--SERVIDOR -> SRVHWDBTS24
USE BDPRACTICAS
GO

CREATE PROCEDURE ENCUESTA.ISP_CREAR_ENCUESTA
(
@NOMBRE_ENCUESTA VARCHAR(50)
,@DESCRIPCION_ENCUESTA VARCHAR(200)
,@TIPO_ENCUESTA_ID INT
,@TIPO_PROGRAMA_ID VARCHAR(20)
,@SEDE_ID VARCHAR(20)
,@PERIODO_ID VARCHAR(20)
,@SECCION_ID VARCHAR(30)
,@FECHA_INICIO DATETIME
,@FECHA_FIN DATETIME
,@COMPLETADO BIT
,@ACTIVO BIT
,@ESTADO BIT
,@FECHA_CREACION DATETIME
,@USUARIO_CREACION VARCHAR(50)
)
AS
BEGIN

	DECLARE @ENCUESTA_ID INT;

	INSERT INTO ENCUESTA.ENCUESTA (
	NOMBRE_ENCUESTA
	,DESCRIPCION_ENCUESTA
	,TIPO_ENCUESTA
	,TIPO_PROGRAMA
	,SEDE
	,PERIODO
	,SECCION
	,FECHA_INICIO
	,FECHA_FIN
	,COMPLETADO
	,ACTIVO
	,ESTADO
	,FECHA_CREACION
	,USUARIO_CREACION
	)
	VALUES (
	@NOMBRE_ENCUESTA
	,@DESCRIPCION_ENCUESTA
	,@TIPO_ENCUESTA_ID
	,@TIPO_PROGRAMA_ID
	,@SEDE_ID
	,@PERIODO_ID
	,@SECCION_ID
	,@FECHA_INICIO
	,@FECHA_FIN
	,@COMPLETADO
	,@ACTIVO
	,@ESTADO
	,@FECHA_CREACION
	,@USUARIO_CREACION
	)

	SET @ENCUESTA_ID = SCOPE_IDENTITY();
	SELECT @ENCUESTA_ID;

END

GO
CREATE PROCEDURE ENCUESTA.ISP_CREAR_BLOQUE
(
@ENCUESTA_ID INT
,@TITULO_BLOQUE VARCHAR(200)
,@ORDEN INT
,@ESTADO BIT
,@FECHA_CREACION DATETIME
,@USUARIO_CREACION VARCHAR(50)
)
AS
BEGIN

	DECLARE @BLOQUE_ID INT;

	INSERT INTO ENCUESTA.ENCUESTA_BLOQUE (
	ENCUESTA_ID
	,TITULO_BLOQUE
	,ORDEN
	,ESTADO
	,FECHA_CREACION
	,USUARIO_CREACION
	)
	VALUES (
	@ENCUESTA_ID
	,@TITULO_BLOQUE
	,@ORDEN
	,@ESTADO
	,@FECHA_CREACION
	,@USUARIO_CREACION
	)

	SET @BLOQUE_ID = SCOPE_IDENTITY();
	SELECT @BLOQUE_ID;

END

GO
CREATE PROCEDURE ENCUESTA.ISP_CREAR_PREGUNTA
(
@BLOQUE_ID INT
,@TEXTO_PREGUNTA VARCHAR(200)
,@TIPO_PREGUNTA VARCHAR(MAX)
,@ORDEN INT
,@OPCIONES_JSON VARCHAR(MAX)
,@ESTADO BIT
,@FECHA_CREACION DATETIME
,@USUARIO_CREACION VARCHAR(50)
)
AS
BEGIN

	INSERT INTO ENCUESTA.ENCUESTA_PREGUNTA (
	BLOQUE_ID
	,TEXTO_PREGUNTA
	,TIPO_PREGUNTA
	,ORDEN
	,OPCIONES_JSON
	,ESTADO
	,FECHA_CREACION
	,USUARIO_CREACION
	)
	VALUES (
	@BLOQUE_ID
	,@TEXTO_PREGUNTA
	,@TIPO_PREGUNTA
	,@ORDEN
	,@OPCIONES_JSON
	,@ESTADO
	,@FECHA_CREACION
	,@USUARIO_CREACION
	)

END

GO
CREATE PROCEDURE ENCUESTA.SSP_LISTAR_ENCUESTAS
(
    @PageNumber INT = 1,
    @PageSize   INT = 10
)
AS
BEGIN

	;WITH CTE AS
		(
			SELECT
				 T1.ENCUESTA_ID
				,T1.NOMBRE_ENCUESTA
				,T1.DESCRIPCION_ENCUESTA
				,'TIPO PROGRAMA' AS TIPO_PROGRAMA -- pendiente cruzar con tabla tipo programa
				,T2.NOMBRE_ENCUESTA AS NOMBRE_TIPO_ENCUESTA
				,T1.FECHA_CREACION
				,T1.COMPLETADO
			FROM ENCUESTA.ENCUESTA T1
			INNER JOIN ENCUESTA.TIPO_ENCUESTA T2 ON T1.TIPO_ENCUESTA = T2.TIPO_ENCUESTA_ID
			--FALTA CRUZAR CON LA TABLA TIPO PROGRAMA CON EL MAESTRO
			WHERE T1.ESTADO = 1
		)
		SELECT *
		FROM CTE
		ORDER BY FECHA_CREACION DESC
		OFFSET (@PageNumber - 1) * @PageSize ROWS
		FETCH NEXT @PageSize ROWS ONLY;

END

GO
CREATE PROCEDURE ENCUESTA.SSP_LISTAR_TIPO_ENCUESTA
AS
BEGIN

	SELECT
		TIPO_ENCUESTA_ID
		,NOMBRE_ENCUESTA
	FROM ENCUESTA.TIPO_ENCUESTA
	WHERE ESTADO = 1

END

GO
CREATE PROCEDURE ENCUESTA.SSP_LISTAR_SEDES
AS
BEGIN

	SELECT
		codSede AS SEDE_ID
		,UPPER(nombreSede) AS NOMBRE_SEDE
	FROM GRA.tblSede
	WHERE ESTADO = 1

END

GO
CREATE PROCEDURE ENCUESTA.SSP_LISTAR_PERIODOS
AS
BEGIN

	SELECT DISTINCT TOP 9
		idPerAcad AS PERIODO_ID
		,idPerAcad AS NOMBRE_PERIODO
	FROM OCL.tblEgresado
	--WHERE	-- ->FILTRAR POR CANTIDAD DE PERIODOS QUE SE QUIEREN LISTAR, NO HAY FLAG ACTIVO
	ORDER BY idPerAcad DESC

END

GO
--CREATE PROCEDURE ENCUESTA.SSP_LISTAR_TIPO_PROGRAMA
--AS
--BEGIN

--	SELECT
--		1 AS TIPO_PROGRAMA_ID
--		,'TIPO PROGRAMA' AS NOMBRE_PROGRAMA
--	--FROM ENCUESTA.TIPO_ENCUESTA
--	--WHERE ESTADO = 1

--END

GO
CREATE PROCEDURE ENCUESTA.SSP_LISTAR_ENCUESTA_ID (@ENCUESTA_ID INT)
AS
BEGIN

	SELECT
		 T1.ENCUESTA_ID
		,T1.NOMBRE_ENCUESTA
		,T1.DESCRIPCION_ENCUESTA
		,'MODULO' AS MODULO
		,'SIN DOCENTE' AS DOCENTE
		,ISNULL(T4.NOMBRE_PROGRAMA, 'SIN PROGRAMA') AS TIPO_PROGRAMA
		,ISNULL(T3.TIPO_ENCUESTA_ID, 0) AS TIPO_ENCUESTA_ID
		,ISNULL(T3.NOMBRE_ENCUESTA, 'SIN TIPO ENCUESTA') AS TIPO_ENCUESTA
		,ISNULL(T2.nombreSede, 'SIN SEDE') AS SEDE
		,ISNULL(T1.PERIODO, 'SIN PERIODO') AS PERIODO
		,ISNULL(T1.SECCION, 'SIN SECCION') AS SECCION
		,T1.FECHA_INICIO
		,T1.FECHA_FIN
		,T1.COMPLETADO
		,T1.ACTIVO
		,T1.FECHA_CREACION
	FROM ENCUESTA.ENCUESTA T1
	LEFT JOIN GRA.tblSede T2 ON T1.SEDE = T2.codSede
	LEFT JOIN ENCUESTA.TIPO_ENCUESTA T3 ON T3.TIPO_ENCUESTA_ID = T1.TIPO_ENCUESTA
	LEFT JOIN ENCUESTA.TIPO_PROGRAMA T4 ON T4.TIPO_PROGRAMA_ID = T1.TIPO_PROGRAMA
	WHERE T1.ENCUESTA_ID = @ENCUESTA_ID
		AND T1.ESTADO = 1

	SELECT
		T2.BLOQUE_ID
		,T2.TITULO_BLOQUE
		,T2.ORDEN
	FROM ENCUESTA.ENCUESTA T1
	INNER JOIN ENCUESTA.ENCUESTA_BLOQUE T2 ON T1.ENCUESTA_ID = T2.ENCUESTA_ID
	WHERE T1.ENCUESTA_ID = @ENCUESTA_ID
		AND T2.ESTADO = 1

	SELECT
		T2.BLOQUE_ID
		,T3.PREGUNTA_ID
		,T3.TEXTO_PREGUNTA
		,T3.TIPO_PREGUNTA
		,T3.ORDEN
		,T3.OPCIONES_JSON
	FROM ENCUESTA.ENCUESTA T1
	INNER JOIN ENCUESTA.ENCUESTA_BLOQUE T2 ON T1.ENCUESTA_ID = T2.ENCUESTA_ID
	INNER JOIN ENCUESTA.ENCUESTA_PREGUNTA T3 ON T3.BLOQUE_ID = T2.BLOQUE_ID
	WHERE T1.ENCUESTA_ID = @ENCUESTA_ID
		AND T3.ESTADO = 1

END

GO
CREATE PROCEDURE ENCUESTA.USP_EDITAR_ENCUESTA
(
@ENCUESTA_ID INT
,@NOMBRE_ENCUESTA VARCHAR(200)
,@DESCRIPCION_ENCUESTA VARCHAR(200)
,@TIPO_PROGRAMA VARCHAR(20)
,@TIPO_ENCUESTA INT
,@SEDE VARCHAR(20)
,@PERIODO VARCHAR(20)
,@SECCION VARCHAR(20)
,@FECHA_INICIO DATETIME
,@FECHA_FIN DATETIME
,@ACTIVO BIT
,@COMPLETADO BIT
,@USUARIO_MODIFICACION VARCHAR(50)
,@FECHA_MODIFICACION DATETIME
)
AS
BEGIN

	UPDATE ENCUESTA.ENCUESTA WITH (ROWLOCK)
	SET
		NOMBRE_ENCUESTA = @NOMBRE_ENCUESTA
		,DESCRIPCION_ENCUESTA = @DESCRIPCION_ENCUESTA
		,TIPO_PROGRAMA = @TIPO_PROGRAMA
		,TIPO_ENCUESTA = @TIPO_ENCUESTA
		,SEDE = @SEDE
		,PERIODO = @PERIODO
		,SECCION = @SECCION
		,FECHA_INICIO = @FECHA_INICIO
		,FECHA_FIN = @FECHA_FIN
		,ACTIVO = @ACTIVO	-- VALIDAR SI SE VA A ACTUALIZAR ACA O SÓLO CUANDO SE ENVIÉ LA ENCUESTA CON EL LINK POR CORREO
		,COMPLETADO = @COMPLETADO
		,USUARIO_MODIFICACION = @USUARIO_MODIFICACION
		,FECHA_MODIFICACION = @FECHA_MODIFICACION
	WHERE ENCUESTA_ID = @ENCUESTA_ID;

END


GO
CREATE PROCEDURE ENCUESTA.USP_EDITAR_BLOQUE
(
@BLOQUE_ID INT
,@TITULO_BLOQUE VARCHAR(200)
,@ORDEN INT
,@USUARIO_MODIFICACION VARCHAR(50)
,@FECHA_MODIFICACION DATETIME
)
AS
BEGIN

	UPDATE ENCUESTA.ENCUESTA_BLOQUE WITH (ROWLOCK)
	SET
		TITULO_BLOQUE = @TITULO_BLOQUE
		,ORDEN = @ORDEN
		,USUARIO_MODIFICACION = @USUARIO_MODIFICACION
		,FECHA_MODIFICACION = @FECHA_MODIFICACION
	WHERE BLOQUE_ID = @BLOQUE_ID

END


GO
CREATE PROCEDURE ENCUESTA.USP_EDITAR_PREGUNTA
(
@PREGUNTA_ID INT
,@TEXTO_PREGUNTA VARCHAR(200)
,@TIPO_PREGUNTA VARCHAR(MAX)
,@ORDEN INT
,@OPCIONES_JSON VARCHAR(MAX)
,@USUARIO_MODIFICACION VARCHAR(50)
,@FECHA_MODIFICACION DATETIME
)
AS
BEGIN

	UPDATE ENCUESTA.ENCUESTA_PREGUNTA WITH (ROWLOCK)
	SET
		TEXTO_PREGUNTA = @TEXTO_PREGUNTA
		,TIPO_PREGUNTA = @TIPO_PREGUNTA
		,ORDEN = @ORDEN
		,OPCIONES_JSON = @OPCIONES_JSON
		,USUARIO_MODIFICACION = @USUARIO_MODIFICACION
		,FECHA_MODIFICACION = @FECHA_MODIFICACION
	WHERE PREGUNTA_ID = @PREGUNTA_ID;

END


GO
CREATE PROCEDURE ENCUESTA.USP_ELIMINAR_ENCUESTA
(
@ENCUESTA_ID INT
,@USUARIO_MODIFICACION VARCHAR(50)
,@FECHA_MODIFICACION DATETIME
)
AS
BEGIN

	UPDATE ENCUESTA.ENCUESTA WITH (ROWLOCK)
	SET
		ESTADO = 0
		,USUARIO_MODIFICACION = @USUARIO_MODIFICACION
		,FECHA_MODIFICACION = @FECHA_MODIFICACION
	WHERE ENCUESTA_ID = @ENCUESTA_ID;

	UPDATE ENCUESTA.ENCUESTA_BLOQUE WITH (ROWLOCK)
	SET
		ESTADO = 0
		,USUARIO_MODIFICACION = @USUARIO_MODIFICACION
		,FECHA_MODIFICACION = @FECHA_MODIFICACION
	WHERE ENCUESTA_ID = @ENCUESTA_ID;

	UPDATE T1 WITH (ROWLOCK)
	SET
		ESTADO = 0
		,USUARIO_MODIFICACION = @USUARIO_MODIFICACION
		,FECHA_MODIFICACION = @FECHA_MODIFICACION
	FROM ENCUESTA.ENCUESTA_PREGUNTA T1
	INNER JOIN ENCUESTA.ENCUESTA_BLOQUE T2 ON T1.BLOQUE_ID = T2.BLOQUE_ID
	WHERE T2.ENCUESTA_ID = @ENCUESTA_ID;

END


GO
CREATE PROCEDURE ENCUESTA.USP_ELIMINAR_BLOQUE
(
@BLOQUE_ID INT
,@USUARIO_MODIFICACION VARCHAR(50)
,@FECHA_MODIFICACION DATETIME
)
AS
BEGIN

	UPDATE ENCUESTA.ENCUESTA_BLOQUE WITH (ROWLOCK)
	SET
		ESTADO = 0
		,USUARIO_MODIFICACION = @USUARIO_MODIFICACION
		,FECHA_MODIFICACION = @FECHA_MODIFICACION
	WHERE BLOQUE_ID = @BLOQUE_ID;

	UPDATE ENCUESTA.ENCUESTA_PREGUNTA WITH (ROWLOCK)
	SET
		ESTADO = 0
		,USUARIO_MODIFICACION = @USUARIO_MODIFICACION
		,FECHA_MODIFICACION = @FECHA_MODIFICACION
	WHERE BLOQUE_ID = @BLOQUE_ID;

END


GO
CREATE PROCEDURE ENCUESTA.USP_ELIMINAR_PREGUNTA
(
@PREGUNTA_ID INT
,@USUARIO_MODIFICACION VARCHAR(50)
,@FECHA_MODIFICACION DATETIME
)
AS
BEGIN

	UPDATE ENCUESTA.ENCUESTA_PREGUNTA WITH (ROWLOCK)
	SET
		ESTADO = 0
		,USUARIO_MODIFICACION = @USUARIO_MODIFICACION
		,FECHA_MODIFICACION = @FECHA_MODIFICACION
	WHERE PREGUNTA_ID = @PREGUNTA_ID;

END


GO
CREATE PROCEDURE ENCUESTA.ISP_CREAR_RESPUESTA_ENCUESTA
(
@ENCUESTA_ID INT
,@ALUMNO_ID VARCHAR(50)
,@FECHA_RESPUESTA DATETIME
,@COMPLETADO BIT
)
AS
BEGIN

	DECLARE @RESPUESTA_ENCUESTA_ID INT;

	INSERT INTO ENCUESTA.RESPUESTA_ENCUESTA
	(
		ENCUESTA_ID
		,ALUMNO_ID
		,FECHA_RESPUESTA
		,COMPLETADO
	)
	VALUES
	(
		@ENCUESTA_ID
		,@ALUMNO_ID
		,@FECHA_RESPUESTA
		,@COMPLETADO
	);

	SET @RESPUESTA_ENCUESTA_ID = SCOPE_IDENTITY();
	
	SELECT @RESPUESTA_ENCUESTA_ID AS RESPUESTA_ENCUESTA_ID;

END


GO
CREATE PROCEDURE ENCUESTA.ISP_CREAR_RESPUESTA_PREGUNTA
(
@RESPUESTA_ENCUESTA_ID INT
,@ENCUESTA_PREGUNTA_ID INT
,@VALOR_RESPUESTA NVARCHAR(MAX)
)
AS
BEGIN

	INSERT INTO ENCUESTA.RESPUESTA_PREGUNTA (
		RESPUESTA_ENCUESTA_ID
		,ENCUESTA_PREGUNTA_ID
		,VALOR_RESPUESTA
	)
	VALUES (
		@RESPUESTA_ENCUESTA_ID
		,@ENCUESTA_PREGUNTA_ID
		,@VALOR_RESPUESTA
	);

END


GO
CREATE PROCEDURE ENCUESTA.VALIDAR_RESPUESTA_ALUMNO
(
@ENCUESTA_ID INT
,@ALUMNO_ID VARCHAR(50)
)
AS
BEGIN

	SELECT 1
	FROM ENCUESTA.RESPUESTA_ENCUESTA
	WHERE ENCUESTA_ID = @ENCUESTA_ID
		AND ALUMNO_ID = @ALUMNO_ID
		AND COMPLETADO = 1

END

GO
CREATE PROCEDURE ENCUESTA.VALIDAR_ENCUESTA_ACTIVA
@ENCUESTA_ID INT
AS
BEGIN

	SELECT 1 FROM ENCUESTA.ENCUESTA
	WHERE ENCUESTA_ID = @ENCUESTA_ID
		AND ACTIVO = 1	-- VALIDAR SI ES EL CAMPO DE ENCUESTA ACTIVA O VALIDAR POR FECHA FIN FECHA INICIO

END


GO
CREATE PROCEDURE ENCUESTA.SSP_LISTAR_ENCUESTAS_RESPONDIDAS
    @ALUMNO_ID VARCHAR(50)
AS
BEGIN
    SELECT
        RE.ENCUESTA_ID,
        E.NOMBRE_ENCUESTA,
        RE.FECHA_RESPUESTA,
        RE.COMPLETADO
    FROM ENCUESTA.RESPUESTA_ENCUESTA RE
    INNER JOIN ENCUESTA.ENCUESTA E ON E.ENCUESTA_ID = RE.ENCUESTA_ID
    WHERE RE.ALUMNO_ID = @ALUMNO_ID
    ORDER BY RE.FECHA_RESPUESTA DESC;
END


CREATE PROCEDURE ENCUESTA.SSP_OBTENER_VALORES_CORREO
AS
BEGIN

SELECT
	USER_EMAIL AS FROM_EMAIL
	,TO_EMAIL AS TO_EMAIL
	,NOMBRE_ENCUESTA
	,NSUBJECT AS SUBJECT_CORREO
	,BODY AS BODY_CORREO
FROM ENCUESTA.VALORES_CORREO

END

CREATE PROCEDURE ENCUESTA.ACTUALIZAR_ENCUESTA_ENVIADA
(@ENCUESTA_ID INT
,@USUARIO_ACTUALIZA VARCHAR(100))
AS
BEGIN

	UPDATE ENCUESTA.ENCUESTA
	SET ACTIVO = 1
		,FECHA_MODIFICACION = GETDATE()
		,USUARIO_MODIFICACION = @USUARIO_ACTUALIZA
	WHERE ENCUESTA_ID = @ENCUESTA_ID

END


