-- SERVIDOR -> 20.0.3.240
USE BDUCCI
GO

CREATE SCHEMA ENCUESTA;
GO

CREATE PROCEDURE ENCUESTA.SSP_LISTAR_SECCIONES
AS
BEGIN
	BEGIN TRY
	----DISTINCT SSRBLCK_BLCK_CODE AS "Seccion" 
	--DECLARE @ANIO_ACTUAL INT = CONCAT(YEAR(GETDATE()), '00');
	DECLARE @ANIO_ACTUAL CHAR(4) = CAST(YEAR(GETDATE()) AS CHAR(4));
	DECLARE @ANIO_2DIGITOS CHAR(2) = RIGHT(@ANIO_ACTUAL, 2);

		SELECT TOP 10 --SSRBLCK_TERM_CODE,
				SSRBLCK_BLCK_CODE AS SECCION_ID
				,SMRPRLE_DESCRIPTION AS NOMBRE_SECCION
		FROM 
		OPENQUERY(DEVL,'	SELECT DISTINCT 
								SSRBLCK_TERM_CODE
								,SSRBLCK_BLCK_CODE
								,SMRPRLE_DESCRIPTION
							FROM SATURN.SSRBLCK BLCK
							INNER JOIN SATURN.SMRPRLE PR 
								ON PR.SMRPRLE_PROGRAM = SUBSTR(BLCK.SSRBLCK_BLCK_CODE, 3, 3)
							WHERE  PR.SMRPRLE_LEVL_CODE IN (''PS'',''EC'',''CO'')')
		--WHERE SSRBLCK_TERM_CODE >= @ANIO_ACTUAL
		WHERE LEFT(SSRBLCK_TERM_CODE,4) = @ANIO_ACTUAL
			AND LEFT(SSRBLCK_BLCK_CODE,2) = @ANIO_2DIGITOS
			AND RIGHT(SSRBLCK_TERM_CODE,2) = '05';
			--AND ESTADO = 1
		
	END TRY
	BEGIN CATCH
		DECLARE	@ErrorMessage VARCHAR(4000),
				@ErrorSeverity INT,
				@ErrorState INT;
		SELECT	@ErrorMessage = ERROR_MESSAGE(),
				@ErrorSeverity = ERROR_SEVERITY(),
				@ErrorState = ERROR_STATE();
				RAISERROR(@ErrorMessage,@ErrorSeverity,@ErrorState);
	END CATCH
END

GO
CREATE PROCEDURE ENCUESTA.SSP_LISTAR_TIPO_PROGRAMA
AS
BEGIN
   BEGIN TRY
   DECLARE @QUERY2 NVARCHAR(2000) 
   DECLARE @TS_QUERY VARCHAR(MAX)
   DECLARE @BDOracle VARCHAR(10) = 'DEVL'

   SET @QUERY2= '
   SELECT
   DISTINCT SSBSECT_SUBJ_CODE AS TIPO_PROGRAMA_ID,
       (CASE WHEN SSBSECT_SUBJ_CODE = ''''PSDP'''' THEN ''''DIPLOMAS''''
             WHEN SSBSECT_SUBJ_CODE = ''''PSEV'''' THEN ''''EVENTOS''''
             WHEN SSBSECT_SUBJ_CODE = ''''PSMA'''' THEN ''''MAESTRIA''''
             WHEN SSBSECT_SUBJ_CODE = ''''PSPA'''' THEN ''''PASANTIA''''
             WHEN SSBSECT_SUBJ_CODE = ''''PSPE'''' THEN ''''PROGRAMAS DE ESPECIALIZACION''''
             WHEN SSBSECT_SUBJ_CODE = ''''PSCC'''' THEN ''''CURSO CERRADO''''
             WHEN SSBSECT_SUBJ_CODE = ''''PSCU'''' THEN ''''CURSO''''
             WHEN SSBSECT_SUBJ_CODE = ''''PSDI'''' THEN ''''DIPLOMADO''''
             WHEN SSBSECT_SUBJ_CODE = ''''PSDO'''' THEN ''''DOCTORADO'''' END) AS NOMBRE_PROGRAMA
   FROM SSBSECT
   WHERE SSBSECT_SUBJ_CODE IN (  ''''PSDP''''
								,''''PSEV''''
								,''''PSMA''''
								,''''PSPA''''
								,''''PSPE''''
								,''''PSCC''''
								,''''PSCU''''
								,''''PSDI''''
								,''''PSDO'''')
   '

   SET @TS_QUERY= '
   SELECT TIPO_PROGRAMA_ID, NOMBRE_PROGRAMA
       FROM OPENQUERY(' + @BDOracle + ',''' + @QUERY2 + ''')';
 
   EXEC (@TS_QUERY)
END TRY
BEGIN CATCH
	SELECT 
     ERROR_NUMBER() AS ERROR_NUMBER,
     ERROR_MESSAGE() AS ERROR_MESSAGE
END CATCH
END 




