
--BD BANNER ORACLE

DROP PROCEDURE P_LISTAR_TIPO_PROGRAMA;

DROP PROCEDURE P_LISTAR_SECCIONES;

DROP PROCEDURE P_LISTAR_PERIODOS;

DROP PROCEDURE P_LISTAR_SEDES;

DROP PROCEDURE P_LISTAR_ASIGNATURAS;

DROP PROCEDURE P_LISTAR_DOCENTES_ASIGNATURA;

DROP PROCEDURE P_LISTAR_CORREOS_ENCUESTA;

DROP PROCEDURE P_NOMBRE_DOCENTE_DNI;

DROP PROCEDURE P_LISTAR_ASESORES;

